To fix Restore can fail when at least one partition was empty #17
azapps/kafka-backup pull request #19
Opened 2020-02-28 05:12 UTC by rohan26may

2020-02-28 13:12 UTC, LBmaster001 requested changes
Why Use the Old Java IO, if we already have the NIO used ?
`if (Files.size(topicDir.resolve(segmentFilePrefix) > 0) {
    currentSegment.seek(offset);
}`

2020-02-28 13:15 UTC, itadventurer commented on src/main/java/de/azapps/kafkabackup/common/partition/PartitionReader.java
> +        if (new java.io.File(topicDir.toFile(), segmentFilePrefix).length() != 0) {
I am thinking whether we should check this here or whether the `SegmentReader` is the correct place. Any ideas from your side?

2020-03-04 09:41 UTC, itadventurer commented
I like Olofs approach more: https://github.com/getdreams/kafka-backup/pull/6/files Any objections?

2020-03-04 10:48 UTC, LBmaster001 commented
I don't realy like it, because for me it looks like some kind of workaround and does not fix the real issue here. I tried to explain what I mean here: https://github.com/itadventurer/kafka-backup/issues/17#issuecomment-594429997
Maybe I'm wrong, but this seems to be the better approach for me

2020-03-05 20:48 UTC, itadventurer commented
Merged Olofs solution ;) Thank you for your help!

2020-03-05 20:48 UTC, closed without merging